# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  # Dev Container Updates
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  # Maven Dependencies
  - package-ecosystem: "maven"
    directory: "/Ch06_Source/ch06/ch06-01"
    schedule:
      interval: weekly
    ignore:
      # Ignore patch updates for stable dependencies
      - dependency-name: "org.slf4j:slf4j-api"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "org.apache.logging.log4j:*"
        update-types: ["version-update:semver-patch"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
