spring:
    application:
        name: product-service-api
server:
    port: 8082

zuul:
  routes:
     product-api:
        path: /myapp1/api/**
        service-id: product-service
     product-webapi:
        path: /myapp1/web/**
        service-id: product-web

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 2000

