spring:
   application:
         name: ecom-config
   cloud:
     config:
      server: 
           git:
            uri: file://D:/binil/gold/pack03/ch18/ch18-01/Ax2-Ecom-With-Security/config-repo
server:
  port: 8888

