spring:
   application:
         name: ecom-config
   cloud:
     config:
      server: 
           git:
            uri: file://D:/binil/gold/pack03/ch19/ch19-03/Ax3-Ecom-With-Security/config-repo   
server:
  port: 8888